name: Release
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
      - name: Configure local.properties
        env:
          USERNAME: ${{ github.actor }}
        run: |-
          cat >local.properties <<EOF
          pwsdk.maven.url=https://maven.pkg.github.com/circlefin/w3s-android-sdk
          pwsdk.maven.username=${USERNAME}
          pwsdk.maven.password=${GITHUB_TOKEN}
          EOF
      - run: ./gradlew dependencies

  release-sbom:
    needs: dependencies
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
